export const LANGUAGE_OPTIONS = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "??????" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "???????" },
  { code: "ar", name: "Arabic", nativeName: "???????" },
  { code: "bn", name: "Bengali", nativeName: "?????" },
  { code: "ur", name: "Urdu", nativeName: "????" },
  { code: "ja", name: "Japanese", nativeName: "???" },
  { code: "ko", name: "Korean", nativeName: "???" },
  { code: "zh", name: "Chinese", nativeName: "??" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "ta", name: "Tamil", nativeName: "?????" }
];

export const DEFAULT_UI_COPY = {
  tagline: "Hatch your understanding",
  themeDarkQuest: "Dark Quest",
  themeSunnyQuest: "Sunny Quest",
  themeMoonOn: "Moon On",
  themeSunOn: "Sun On",
  heroTitle: "Learn with long-form teaching, revision cards, and mastery checks.",
  heroBody: "Eggzy now teaches in a fuller journey: deep explanation slides, revision flashcards, MCQ quiz practice, and a teach-back review that spots missing ideas and reteaches them.",
  heroLessons: "Lesson slides",
  heroQuiz: "Quiz mode",
  heroRevise: "Flashcards + teach-back",
  heroMascotTitle: "Eggzy reteaches when you slow down.",
  heroMascotBody: "Long pauses on quiz items, missing concepts in teach-back, and shaky explanations become cues for reteaching.",
  learnerSetupEyebrow: "Learner Setup",
  learnerSetupTitle: "Tell Eggzy how you learn best",
  interestHook: "Interest hook",
  language: "Language",
  learnerName: "Learner name",
  optional: "Optional",
  currentMentalState: "Current mental state",
  explanationStyle: "Preferred explanation style",
  chooseConceptEyebrow: "Choose A Concept",
  chooseConceptTitle: "Start with a topic and let Eggzy teach it step by step",
  conceptPlaceholder: "Examples: fractions, photosynthesis, black holes, microprocessor, blockchain",
  teachMe: "Teach Me",
  teaching: "Teaching...",
  currentMission: "Current Mission",
  learnerSnapshot: "Learner snapshot",
  level: "Level",
  mood: "Mood",
  style: "Style",
  interest: "Interest",
  lessonNavigationEyebrow: "Lesson Navigation",
  lessonNavigationTitle: "Walk through the concept one full screen at a time",
  confusionHotspots: "Confusion hotspots",
  adaptiveCoaching: "Adaptive coaching",
  flashcards: "Flashcards",
  reviseQuick: "Revise with quick flips",
  tapPrompt: "Tap to see prompt",
  tapReveal: "Tap to reveal answer",
  previous: "Previous",
  next: "Next",
  quizMode: "Quiz Mode",
  quizTitle: "MCQ practice with hesitation tracking",
  score: "Score",
  needsReteach: "Needs reteach",
  hesitationTitle: "Eggzy noticed hesitation",
  teachTopicEyebrow: "Teach The Topic",
  teachTopicTitle: "Write a full paragraph and let Eggzy spot missing ideas",
  yesMostly: "Yes, mostly",
  notYet: "Not yet",
  slowQuestions: "Slow questions tracked",
  noneYet: "None yet",
  teachBackPlaceholder: "Teach the topic back in a full paragraph. Eggzy will check what you explained well, what you missed, and what to reteach.",
  confusionPlaceholder: "Still confused about...",
  evaluateUnderstanding: "Evaluate Understanding",
  checking: "Checking...",
  eggzySays: "Eggzy says",
  overlapScore: "Concept overlap score",
  teachBackAnalysis: "Teach-back analysis",
  strong: "Strong",
  missing: "Missing",
  reteach: "Reteach",
  reverseTeachingBank: "Reverse Teaching Bank",
  reverseTeachingTitle: "Questions created from weak spots and skipped ideas",
  starterLibraryEyebrow: "Starter Library",
  starterLibraryTitle: "Browse Eggzy's ready-made quests",
  elementary: "Elementary",
  intermediate: "Intermediate",
  advanced: "Advanced",
  elementarySublabel: "Ages 6-10",
  intermediateSublabel: "Build the basics",
  advancedSublabel: "Domain expertise",
  elementaryDescription: "Simple language, vivid analogies",
  intermediateDescription: "Structured, jargon-free clarity",
  advancedDescription: "Technical depth and nuance",
  elementaryExplanation: "Elementary explanation",
  intermediateExplanation: "Intermediate explanation",
  advancedExplanation: "Advanced explanation",
  analogyLens: "Analogy Lens",
  stepByStepLens: "Step-by-Step Lens",
  realLifeLens: "Real-Life Lens",
  moods: {
    focused: "Focused",
    curious: "Curious",
    overwhelmed: "Overwhelmed",
    tired: "Tired"
  },
  styles: {
    analogy: "Analogy",
    story: "Story",
    technical: "Technical",
    simple: "Simple"
  }
};
